// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn5YHI5mDlxVsJduO80oBpYIcR4expjIs',
    appId: '1:956634705622:web:f01e750e0deda15522e377',
    messagingSenderId: '956634705622',
    projectId: 'mondu-farm',
    authDomain: 'mondu-farm.firebaseapp.com',
    databaseURL: 'https://mondu-farm-default-rtdb.firebaseio.com',
    storageBucket: 'mondu-farm.appspot.com',
    measurementId: 'G-44EVYGEZGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFQMBdB4aCazXgXt0rlp9VYZzNpxuVXE',
    appId: '1:956634705622:android:ca9aa8a746534b3a22e377',
    messagingSenderId: '956634705622',
    projectId: 'mondu-farm',
    databaseURL: 'https://mondu-farm-default-rtdb.firebaseio.com',
    storageBucket: 'mondu-farm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA8mmgWXPzJ4noiHF_Xzn7o0lArijkIfY',
    appId: '1:956634705622:ios:837b3aa329614b8d22e377',
    messagingSenderId: '956634705622',
    projectId: 'mondu-farm',
    databaseURL: 'https://mondu-farm-default-rtdb.firebaseio.com',
    storageBucket: 'mondu-farm.appspot.com',
    iosBundleId: 'com.example.monduFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA8mmgWXPzJ4noiHF_Xzn7o0lArijkIfY',
    appId: '1:956634705622:ios:8b1f26f9583f830722e377',
    messagingSenderId: '956634705622',
    projectId: 'mondu-farm',
    databaseURL: 'https://mondu-farm-default-rtdb.firebaseio.com',
    storageBucket: 'mondu-farm.appspot.com',
    iosBundleId: 'com.example.monduFarm.RunnerTests',
  );
}
